name: refilla
description: "Refilla is your smart assistant for managing kitchen and household inventory. Track what’s in stock, get alerts for low or out-of-stock items, and create smart grocery lists in seconds."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true